---

host: 127.0.0.1
port: 8888
planner: plugins.dark.app.smart
stores:
  - plugins/stockpile/payloads
  - plugins/adversary/payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
  - dark
users:
  admin: admin
